/*
NEW Tyk DASH API

Testing CertsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package dashboard

import (
	"context"
	openapiclient "github.com/TykTechnologies/dashboard-sdk"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_dashboard_CertsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CertsAPIService CreateCertificates", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CertsAPI.CreateCertificates(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CertsAPIService DeleteCertificateDependencies", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var certId string

		resp, httpRes, err := apiClient.CertsAPI.DeleteCertificateDependencies(context.Background(), certId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CertsAPIService DeleteCertificates", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var certId string

		resp, httpRes, err := apiClient.CertsAPI.DeleteCertificates(context.Background(), certId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CertsAPIService GetCertificate", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var certId string

		resp, httpRes, err := apiClient.CertsAPI.GetCertificate(context.Background(), certId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CertsAPIService GetCertificateDependencies", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var certId string

		resp, httpRes, err := apiClient.CertsAPI.GetCertificateDependencies(context.Background(), certId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CertsAPIService ListCertificates", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CertsAPI.ListCertificates(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CertsAPIService ListDetailedCertificates", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CertsAPI.ListDetailedCertificates(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
