name: Run Live Gateway And Dashboard
on:
  push:
    branches:
      - re-run

jobs:
  run-test-with-live-gateway:
    runs-on: ubuntu-latest
    name: Example

    steps:
      # Checkout the current repository code
      - name: Checkout current repository
        uses: actions/checkout@v4

      # Checkout the TykTechnologies/tyk repository into a sub-folder
      - name: Checkout Tyk repository
        uses: actions/checkout@v4
        with:
          repository: TykTechnologies/tyk
          path: tyk-repo # Clone Tyk repo into a subfolder

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image using the current repo's dev.dockerfile
      - name: Build Tyk Docker image
        run: |
          ls -a
          docker build -t internal/tyk-gateway -f ./dev.Dockerfile ./tyk-repo

      # Install Docker Compose version 2.29.2
      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker compose --version

      # Start services using docker-compose.yml
      - name: Run docker-compose
        run: |
          docker compose up -d  # Use docker-compose to start the services
          sleep 10
          docker compose logs

      # Check if the services are up and running
      - name: Wait for the gateway to be ready
        run: |
          for i in {1..30}; do
          response=$(curl -s -o /dev/null -w "%{http_code}" \
           -H "x-tyk-authorization: 28d220fd77974a4facfb07dc1e49c2aa" \
           http://localhost:8080/tyk/reload)
          if [ "$response" -eq 200 ]; then
           echo "Gateway is up and running!"
           break
          else
           echo "Gateway not ready yet. HTTP status code: $response"
           sleep 30  # Wait for 30 seconds before retrying
          fi
          done

      # Send request to the Tyk gateway service
      - name: Send request to gateway
        run: |
          curl -X GET http://localhost:8080/tyk/reload \
          -H "Content-Type: application/json" \
          -H "x-tyk-authorization: 28d220fd77974a4facfb07dc1e49c2aa" \

      # Optionally shut down docker-compose services after the tests
      - name: Shutdown docker-compose
        if: always()
        run: |
          docker compose down
